# Generated by Django 5.1.3 on 2024-11-21 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lugar', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('venta', 'En Venta'), ('alquiler', 'En Alquiler')], max_length=10)),
                ('banios', models.PositiveIntegerField()),
                ('cuartos', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='propiedades/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
