# Generated by Django 5.1.3 on 2024-11-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='usuario',
            new_name='propietario',
        ),
    ]
