# Generated by Django 5.1.3 on 2024-11-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
